### ISSUE TITLE
DLsite GenreTag Replacer - Firefox Addon not working

### ISSUE THREAD

**Issue by RedAISkye** [nanami-v2/DLsiteGenreTagReplacer#46]
The [Firefox addon](https://addons.mozilla.org/en-US/firefox/addon/dlsite-genretag-replacer/) doesn't work at all even after I let it always be enabled for DLsite.

Please update your addon with the help of this changelist:-
[reddit.com/r/visualnovels/comments/1by0dka/dlsite_march_2024_tag_changes_for_japanese_and](https://www.reddit.com/r/visualnovels/comments/1by0dka/dlsite_march_2024_tag_changes_for_japanese_and)

**Comment by nanami-v2** [comment]
@RedAISkye 

Thank you for letting me know about this bug.

I'll fix this bug, add en version lang file for replace genre word.
Please wait a few days.

**Comment by nanami-v2** [comment]
@RedAISkye 

This bug was fixed v1.1.0 (English page is supported).
And in v1.1.0, context menu is written in English when browser language is not Japanese.

![image](https://github.com/nanami-v2/DLsiteGenreTagReplacer/assets/49963032/a817df6c-c946-4975-9a4b-7ad26b3c8e95)

**Comment by RedAISkye** [comment]
> @RedAISkye
> 
> Sorry I made for you wait.
> 
> This bug was fixed in v1.1.0 (English page is supported). And in v1.1.0, context menu is written in English when browser language is not Japanese.
> 
> ![image](https://private-user-images.githubusercontent.com/49963032/337376363-a817df6c-c946-4975-9a4b-7ad26b3c8e95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTkyMjMsIm5iZiI6MTcxNzY5ODkyMywicGF0aCI6Ii80OTk2MzAzMi8zMzczNzYzNjMtYTgxN2RmNmMtYzk0Ni00OTc1LTlhNGItN2FkMjZiM2M4ZTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE4MzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNmQyOTdiYzRkYjA3ODM4MDY2NWYwMDU0M2FmMTM2ZWQyOWI4MTdiMGNhMDcxYTdkMTAzMWJlMmYxNDdjZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-YlcRuRsQDBnd8Grj-4hEcVzjv3S86EWj4iS91Uw8Hk)
> 
> If you find again another bugs, I would appreciate if you could report them. Thank you.

No worries, I appreciate your efforts!
Thanks a lot for the update! It's working perfectly now!
